### ISSUE TITLE
Conflict with Runes of wizardry and baubles

### ISSUE THREAD

**Issue by charlescannon** [TeamDman/Animus#61]
Adding animus 2.0.2 causes Runes of wizardry and Baubles to throw errors of 

Caused by: java.lang.NoClassDefFoundError: com/zpig333/runesofwizardry/item/ItemInscriptionBauble
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more

Caused by: java.lang.NoClassDefFoundError: baubles/api/IBauble
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

**Comment by Saereth** [comment]
can you provide the complete log please, nothing in here has any reference to animus nor are we currently doing anything with baubles or that mod

**Comment by charlescannon** [comment]
Thanks for the heads up that your mod isn't doing anything with the other two. Just double checking as it only happens with animus installed. 

Full crash log if you happen to think it warrants looking over still. 
https://pastebin.com/C5SAp0Me

**Comment by TeamDman** [comment]
Fixed
https://github.com/Xilef11/Runes-of-Wizardry/issues/47#issuecomment-401033822
