### ISSUE TITLE
Ritual of Sol crashing with tiny chest

### ISSUE THREAD

**Issue by Hatmic98** [TeamDman/Animus#82]
When activating the ritual of sol with a sigil of the blood lamp in a tiny chest the server crashes. Cant provide logs and such unfortunately because I'm not the server's admin. but this *should* be easily repeatable.

**Comment by TeamDman** [comment]
Just to confirm, do you know which mod the tiny chest is from?

**Comment by Hatmic98** [comment]
It's the mini chest from Extra Utilities 2

**Comment by druidbruce** [comment]
A similar crash so im posting here.
Basically everything is the same, just replace tiny chest with gold chest
crash report:
Description: Ticking block entity

java.lang.ClassCastException: cpw.mods.ironchest.common.tileentity.chest.TileEntityGoldChest cannot be cast to net.minecraft.tileentity.TileEntityChest
	at com.teamdman.animus.rituals.RitualSol.performRitual(RitualSol.java:52)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:196)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:69)
	at WayofTime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:18)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

replicatable
